bump:
  const version: Mailgun_Subscriptions/Plugin.php
  stable tag: readme.txt
  version: mailgun-subscriptions.php
dest:
  lang: languages/
language:
  domain: mailgun-subscriptions
  team: Flightless
  translator: Flightless
watch:
  php:
    - Mailgun_Subscriptions/**/*.php
    - '*.php'
